/**
 * @file    UdsConfig_Generated.c
 * @brief   UDS Diagnostic Configuration Implementation (Auto-generated)
 * @author  UDS Generator
 * @date    2026-03-15 16:49:54
 * 
 * DO NOT EDIT THIS FILE MANUALLY!
 * This file is auto-generated from UDS_Config.xlsx
 */

#include "UdsConfig_Generated.h"
#include <string.h>

/*==================================================================================================
 *                              Internal Data Storage
 *=================================================================================================*/

/* DID Data Storage */
static uint8 Uds_DidData_VIN[17] = {0x56, 0x49, 0x4E, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20};
static uint8 Uds_DidData_ECU_Name[16] = {0x45, 0x43, 0x55, 0x5F, 0x4E, 0x61, 0x6D, 0x65, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20};
static uint8 Uds_DidData_SystemState[4] = {0x00, 0x00, 0x00, 0x00};
static uint8 Uds_DidData_VehicleSpeed[2] = {0x00, 0x00};
static uint8 Uds_DidData_EngineTemp[1] = {0x00};
static uint8 Uds_DidData_SupplierCode[4] = {0x53, 0x75, 0x70, 0x70};
static uint8 Uds_DidData_SW_Version[8] = {0x53, 0x57, 0x5F, 0x56, 0x65, 0x72, 0x73, 0x69};
static uint8 Uds_DidData_HW_Version[8] = {0x48, 0x57, 0x5F, 0x56, 0x65, 0x72, 0x73, 0x69};

/* Session Configuration Table */
typedef struct {
    uint8  sessionType;
    uint16 p2Max;
    uint16 p2StarMax;
    uint16 s3Client;
    uint16 s3Server;
    uint32 supportedServices;
} Uds_SessionConfigType;

static const Uds_SessionConfigType Uds_SessionTable[] = {
    { /* DefaultSession */
        .sessionType = 0x01,
        .p2Max = 50,
        .p2StarMax = 5000,
        .s3Client = 2000,
        .s3Server = 5000,
        .supportedServices = (1UL<<0x10) | (1UL<<0x11) | (1UL<<0x19) | (1UL<<0x22) | (1UL<<0x3E)
    },
    { /* ProgrammingSession */
        .sessionType = 0x02,
        .p2Max = 50,
        .p2StarMax = 5000,
        .s3Client = 2000,
        .s3Server = 5000,
        .supportedServices = (1UL<<0x10) | (1UL<<0x11) | (1UL<<0x27) | (1UL<<0x31) | (1UL<<0x34) | (1UL<<0x35) | (1UL<<0x36) | (1UL<<0x37)
    },
    { /* ExtendedSession */
        .sessionType = 0x03,
        .p2Max = 50,
        .p2StarMax = 5000,
        .s3Client = 2000,
        .s3Server = 5000,
        .supportedServices = (1UL<<0x10) | (1UL<<0x11) | (1UL<<0x19) | (1UL<<0x22) | (1UL<<0x2E) | (1UL<<0x27) | (1UL<<0x31) | (1UL<<0x3E)
    },
};

/* DID Configuration Table - Compatible with Dcm_DidInfoType */
typedef struct {
    uint16  Did;
    uint8*  Data;
    uint16  DataLength;
    boolean IsReadOnly;
} Uds_DidInfoType;

/* Additional DID properties */
typedef struct {
    uint16  Did;
    uint8   securityLevel;
    uint8   sessionMask;
} Uds_DidPropType;

static const Uds_DidInfoType Uds_DidTable[] = {
    { /* 0xF190 - 车辆识别号 */
        .Did = 0xF190,
        .Data = Uds_DidData_VIN,
        .DataLength = 17,
        .IsReadOnly = TRUE
    },
    { /* 0xF197 - ECU名称 */
        .Did = 0xF197,
        .Data = Uds_DidData_ECU_Name,
        .DataLength = 16,
        .IsReadOnly = TRUE
    },
    { /* 0xF100 - 系统状态 */
        .Did = 0xF100,
        .Data = Uds_DidData_SystemState,
        .DataLength = 4,
        .IsReadOnly = FALSE
    },
    { /* 0x0100 - 车速 */
        .Did = 0x0100,
        .Data = Uds_DidData_VehicleSpeed,
        .DataLength = 2,
        .IsReadOnly = FALSE
    },
    { /* 0x0105 - 发动机温度 */
        .Did = 0x0105,
        .Data = Uds_DidData_EngineTemp,
        .DataLength = 1,
        .IsReadOnly = FALSE
    },
    { /* 0xF193 - 供应商代码 */
        .Did = 0xF193,
        .Data = Uds_DidData_SupplierCode,
        .DataLength = 4,
        .IsReadOnly = TRUE
    },
    { /* 0xF194 - 软件版本 */
        .Did = 0xF194,
        .Data = Uds_DidData_SW_Version,
        .DataLength = 8,
        .IsReadOnly = TRUE
    },
    { /* 0xF195 - 硬件版本 */
        .Did = 0xF195,
        .Data = Uds_DidData_HW_Version,
        .DataLength = 8,
        .IsReadOnly = TRUE
    },
};

static const Uds_DidPropType Uds_DidProps[] = {
    { /* 0xF190 */
        .Did = 0xF190,
        .securityLevel = 0x01,
        .sessionMask = 0x07
    },
    { /* 0xF197 */
        .Did = 0xF197,
        .securityLevel = 0x01,
        .sessionMask = 0x07
    },
    { /* 0xF100 */
        .Did = 0xF100,
        .securityLevel = 0x03,
        .sessionMask = 0x06
    },
    { /* 0x0100 */
        .Did = 0x0100,
        .securityLevel = 0x01,
        .sessionMask = 0x07
    },
    { /* 0x0105 */
        .Did = 0x0105,
        .securityLevel = 0x01,
        .sessionMask = 0x07
    },
    { /* 0xF193 */
        .Did = 0xF193,
        .securityLevel = 0x01,
        .sessionMask = 0x07
    },
    { /* 0xF194 */
        .Did = 0xF194,
        .securityLevel = 0x01,
        .sessionMask = 0x07
    },
    { /* 0xF195 */
        .Did = 0xF195,
        .securityLevel = 0x01,
        .sessionMask = 0x07
    },
};

/* DTC Configuration Table - Compatible with Dcm_DtcInfoType */
static Dcm_DtcInfoType Uds_DtcTable[] = {
    { /* 0x000100 - 空气质量流量计电路故障 */
        .Dtc = 0x000100U,
        .Status = 0x00,
        .Snapshot = {0},
        .ExtData = {0}
    },
    { /* 0x000101 - 空气质量流量计性能故障 */
        .Dtc = 0x000101U,
        .Status = 0x00,
        .Snapshot = {0},
        .ExtData = {0}
    },
    { /* 0x000300 - 随机/多缸失火 */
        .Dtc = 0x000300U,
        .Status = 0x00,
        .Snapshot = {0},
        .ExtData = {0}
    },
    { /* 0x001601 - 与ECM通信丢失 */
        .Dtc = 0x001601U,
        .Status = 0x00,
        .Snapshot = {0},
        .ExtData = {0}
    },
    { /* 0x001601 - 与ABS通信丢失 */
        .Dtc = 0x001601U,
        .Status = 0x00,
        .Snapshot = {0},
        .ExtData = {0}
    },
};

/*==================================================================================================
 *                              Public Functions
 *=================================================================================================*/

Std_ReturnType UdsConfig_ReadDid(uint16 did, uint8* data, uint16* len)
{
    uint8 i;
    for (i = 0; i < sizeof(Uds_DidTable)/sizeof(Uds_DidTable[0]); i++) {
        if (Uds_DidTable[i].Did == did) {
            if (*len >= Uds_DidTable[i].DataLength) {
                memcpy(data, Uds_DidTable[i].Data, Uds_DidTable[i].DataLength);
                *len = Uds_DidTable[i].DataLength;
                return E_OK;
            }
            return E_NOT_OK;
        }
    }
    return E_NOT_OK;
}

Std_ReturnType UdsConfig_WriteDid(uint16 did, const uint8* data, uint16 len)
{
    uint8 i;
    for (i = 0; i < sizeof(Uds_DidTable)/sizeof(Uds_DidTable[0]); i++) {
        if (Uds_DidTable[i].Did == did) {
            if (Uds_DidTable[i].IsReadOnly) {
                return E_NOT_OK; /* Read-only DID */
            }
            if (len == Uds_DidTable[i].DataLength) {
                memcpy(Uds_DidTable[i].Data, data, len);
                return E_OK;
            }
            return E_NOT_OK;
        }
    }
    return E_NOT_OK;
}

void UdsConfig_Init(void)
{
    /* Initialize DID default values */
    /* VIN: VIN               */
    /* ECU_Name: ECU_Name         */
    /* SupplierCode: Supp */
    /* SW_Version: SW_Versi */
    /* HW_Version: HW_Versi */
    /* Configuration loaded successfully */
}