/**
 * @file    UdsConfig_Generated.h
 * @brief   UDS Diagnostic Configuration (Auto-generated)
 * @author  UDS Generator
 * @date    2026-03-15 16:49:54
 * 
 * DO NOT EDIT THIS FILE MANUALLY!
 * This file is auto-generated from UDS_Config.xlsx
 */

#ifndef UDSCONFIG_GENERATED_H
#define UDSCONFIG_GENERATED_H

#ifdef __cplusplus
extern "C" {
#endif

/*==================================================================================================
 *                              Includes
 *=================================================================================================*/
#include "Dcm.h"
#include "Std_Types.h"

/*==================================================================================================
 *                              Communication Configuration
 *=================================================================================================*/
#define UDS_CAN_REQUEST_FUNC_ID     0x7dfU
#define UDS_CAN_REQUEST_PHY_ID      0x735U
#define UDS_CAN_RESPONSE_ID         0x73dU
#define UDS_CAN_BAUDRATE            500000U

#define UDS_TX_PDU_ID               20U
#define UDS_RX_PDU_ID_FUNC          10U
#define UDS_RX_PDU_ID_PHY           11U

/*==================================================================================================
 *                              Session Configuration
 *=================================================================================================*/

typedef enum {
    UDS_SESSION_DEFAULTSESSION = 0x01,
    UDS_SESSION_PROGRAMMINGSESSION = 0x02,
    UDS_SESSION_EXTENDEDSESSION = 0x03,
    UDS_SESSION_MAX
} Uds_SessionType;

/* Session Timing Parameters (ms) */
#define UDS_P2_MAX_DEFAULTSESSION       50U
#define UDS_P2STAR_MAX_DEFAULTSESSION    5000U
#define UDS_S3_CLIENT_DEFAULTSESSION     2000U
#define UDS_S3_SERVER_DEFAULTSESSION     5000U
#define UDS_P2_MAX_PROGRAMMINGSESSION   50U
#define UDS_P2STAR_MAX_PROGRAMMINGSESSION 5000U
#define UDS_S3_CLIENT_PROGRAMMINGSESSION 2000U
#define UDS_S3_SERVER_PROGRAMMINGSESSION 5000U
#define UDS_P2_MAX_EXTENDEDSESSION      50U
#define UDS_P2STAR_MAX_EXTENDEDSESSION   5000U
#define UDS_S3_CLIENT_EXTENDEDSESSION    2000U
#define UDS_S3_SERVER_EXTENDEDSESSION    5000U

/*==================================================================================================
 *                              DID Configuration
 *=================================================================================================*/
#define UDS_DID_VIN                  0xF190U  /* 车辆识别号 */
#define UDS_DID_ECU_NAME             0xF197U  /* ECU名称 */
#define UDS_DID_SYSTEMSTATE          0xF100U  /* 系统状态 */
#define UDS_DID_VEHICLESPEED         0x0100U  /* 车速 */
#define UDS_DID_ENGINETEMP           0x0105U  /* 发动机温度 */
#define UDS_DID_SUPPLIERCODE         0xF193U  /* 供应商代码 */
#define UDS_DID_SW_VERSION           0xF194U  /* 软件版本 */
#define UDS_DID_HW_VERSION           0xF195U  /* 硬件版本 */

/*==================================================================================================
 *                              Security Access Configuration
 *=================================================================================================*/
#define UDS_SEC_LEVEL1_UNLOCK        0x01U
#define UDS_SEC_LEVEL2_UNLOCK        0x02U

/*==================================================================================================
 *                              Routine Control Configuration
 *=================================================================================================*/
#define UDS_RID_ERASEMEMORY          0xFF01U  /* 擦除内存 */
#define UDS_RID_CHECKPROGRAMMING     0xFF02U  /* 校验编程 */
#define UDS_RID_SELFTEST             0x0203U  /* 自检例程 */

/*==================================================================================================
 *                              DTC Configuration
 *=================================================================================================*/
#define UDS_DTC_MAF_CIRCUIT          0x000100U  /* 空气质量流量计电路故障 */
#define UDS_DTC_MAF_PERFORMANCE      0x000101U  /* 空气质量流量计性能故障 */
#define UDS_DTC_MISFIRE_DETECT       0x000300U  /* 随机/多缸失火 */
#define UDS_DTC_ECM_COMMLOST         0x001601U  /* 与ECM通信丢失 */
#define UDS_DTC_ABS_COMMLOST         0x001601U  /* 与ABS通信丢失 */

/*==================================================================================================
 *                              Function Prototypes
 *=================================================================================================*/
void UdsConfig_Init(void);
void UdsConfig_MainFunction(void);
Std_ReturnType UdsConfig_ReadDid(uint16 did, uint8* data, uint16* len);
Std_ReturnType UdsConfig_WriteDid(uint16 did, const uint8* data, uint16 len);

#ifdef __cplusplus
}
#endif

#endif /* UDSCONFIG_GENERATED_H */